In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

In [ ]:
# index_col 은 필요 없는것 있을때 없앤다.
# iris.data를 하면 원래는 가장 위에 있는 데이터가 columns가 되는데 read_csv() 안에 header = None 을 하면 columns에서 내려온다. 

In [27]:
path = "C:/Users/choha/Downloads/iris/iris.data"
df = pd.read_csv(path,header=None)
df.columns =  ["sepal length","sepal width","petal length","petal width","class"]
df

sepal length  sepal width  petal length  petal width           class
0             5.1          3.5           1.4          0.2     Iris-setosa
1             4.9          3.0           1.4          0.2     Iris-setosa
2             4.7          3.2           1.3          0.2     Iris-setosa
3             4.6          3.1           1.5          0.2     Iris-setosa
4             5.0          3.6           1.4          0.2     Iris-setosa
..            ...          ...           ...          ...             ...
145           6.7          3.0           5.2          2.3  Iris-virginica
146           6.3          2.5           5.0          1.9  Iris-virginica
147           6.5          3.0           5.2          2.0  Iris-virginica
148           6.2          3.4           5.4          2.3  Iris-virginica
149           5.9          3.0           5.1          1.8  Iris-virginica

[150 rows x 5 columns]

In [35]:

path = "C:/Users/choha/Downloads/iris.csv"
df = pd. read_csv(path)
df

Unnamed: 0  sepal length (cm)  sepal width (cm)  petal length (cm)  \
0             0                5.1               3.5                1.4   
1             1                4.9               3.0                1.4   
2             2                4.7               3.2                1.3   
3             3                4.6               3.1                1.5   
4             4                5.0               3.6                1.4   
..          ...                ...               ...                ...   
145         145                6.7               3.0                5.2   
146         146                6.3               2.5                5.0   
147         147                6.5               3.0                5.2   
148         148                6.2               3.4                5.4   
149         149                5.9               3.0                5.1   

     petal width (cm)  label  
0                 0.2      0  
1                 0.2      0  
2                 0.2      0  
3                 0.2      0  
4                 0.2      0  
..                ...    ...  
145               2.3      2  
146               1.9      2  
147               2.0      2  
148               2.3      2  
149               1.8      2  

[150 rows x 6 columns]

In [51]:
df.value_counts().sum()

150

In [28]:
y = df["class"]


In [29]:
X = df.drop("class",axis = 1)

In [11]:
X.columns

Index(['sepal length (cm)', 'sepal width (cm)', 'petal length (cm)',
       'petal width (cm)'],
      dtype='object')

In [39]:
from sklearn.model_selection import train_test_split

X_train, X_test, y_train, y_test = train_test_split(X,y, test_size = 0.25, random_state = 0)

In [49]:
X_train.value_counts().sum()

112

In [47]:
X_test.value_counts().sum()

38

In [36]:
from sklearn.linear_model import LogisticRegression
from sklearn.svm import SVC
from sklearn.neural_network import MLPClassifier
from sklearn.tree import DecisionTreeClassifier
from sklearn.metrics import accuracy_score
from sklearn.metrics import confusion_matrix

In [40]:
clf_lr = LogisticRegression(random_state=0)
clf_lr.fit(X_train,y_train)

pred_lr = clf_lr.predict(X_test)

print('\n ------ Logistic Regression Classifier------')
print(accuracy_score(y_test,pred_lr))
print(confusion_matrix(y_test, pred_lr))


 ------ Logistic Regression Classifier------
0.9736842105263158
[[13  0  0]
 [ 0 15  1]
 [ 0  0  9]]


In [52]:
from sklearn.svm import SVC

clf_svm = SVC(random_state=0)
clf_svm.fit(X_train,y_train)

pred_svm = clf_svm.predict(X_test)

print("\n-------- SVM Classifier---")
print(accuracy_score(y_test,pred_svm))
print(confusion_matrix(y_test,pred_svm))


-------- SVM Classifier---
0.9736842105263158
[[13  0  0]
 [ 0 15  1]
 [ 0  0  9]]


In [53]:
clf_nn = MLPClassifier(random_state= 0)
clf_nn.fit(X_train,y_train)
pred_nn = clf_nn.predict(X_test)

print("\n---- Nerual Network Classifier --- ")
print(accuracy_score(y_test,pred_nn))
print(confusion_matrix(y_test,pred_nn))


---- Nerual Network Classifier --- 
0.9736842105263158
[[13  0  0]
 [ 0 15  1]
 [ 0  0  9]]


C:\Users\choha\anaconda3\Lib\site-packages\sklearn\neural_network\_multilayer_perceptron.py:691: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (200) reached and the optimization hasn't converged yet.
  warnings.warn(


In [54]:
clf_dt = DecisionTreeClassifier(random_state = 0)
clf_dt.fit(X_train,y_train)
pred_dt = clf_dt.predict(X_test)

print("\n ------ Decision Tree Classifier ----")
print(accuracy_score(y_test,pred_dt))
print(confusion_matrix(y_test,pred_dt))


 ------ Decision Tree Classifier ----
0.9736842105263158
[[13  0  0]
 [ 0 15  1]
 [ 0  0  9]]


In [55]:
from sklearn.ensemble import RandomForestClassifier
from sklearn.metrics import accuracy_score
import warnings
warnings.filterwarnings('ignore')

In [56]:
print("\n ---- Random Forest ---")
rf_clf = RandomForestClassifier(random_state = 0)
rf_clf.fit(X_train,y_train)

pred_clf = rf_clf.predict(X_test)
print(accuracy_score(y_test,pred_clf))
print(confusion_matrix(y_test,pred_clf))


 ---- Random Forest ---
0.9736842105263158
[[13  0  0]
 [ 0 15  1]
 [ 0  0  9]]
